# Config file for automatic testing at travis-ci.org

# See http://docs.travis-ci.com/user/languages/cpp/ for details.

language: cpp

cache:
  apt: true

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - libboost1.55-all-dev
    - autoconf
    - libhdf5-dev
    - libfftw3-dev
    - libgsl0-dev
    - libblas-dev
    - liblapack-dev

compiler:
  # - clang
  - gcc

before_install:
  # - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  # - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  # - sudo apt-get install libhdf5-serial-dev
  - sudo apt-get install libccfits-dev
  # - sudo apt-get install autoconf
  - ./install-Healpix.sh
  # - sudo apt-get install libfftw3-dev libgsl0-dev liblapack-dev libblas-dev
  # - sudo apt-get install libboost1.55-all-dev
  - grep "#define BOOST_VERSION " /usr/include/boost/version.hpp
  # - sudo apt-get install libroot-math-minuit-dev
  - ./install-Minuit2.sh
  - ./install-likely.sh
  - ./install-cosmo.sh

# command to run tests, e.g. python setup.py test
script: scons