# Config file for automatic testing at travis-ci.org

# See http://docs.travis-ci.com/user/languages/cpp/ for details.

language: cpp

compiler:
  # - clang
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"

before_script:
  - sudo apt-get install libhdf5-dev libccfits-dev
  - sudo apt-get install libboost-all-dev

# command to run tests, e.g. python setup.py test
script: scons